# Test
assert isPalindrome("ali")==False
assert isPalindrome("bob")
assert isPalindrome("hannah")
assert isPalindrome("ada")
assert isPalindrome("anna")
assert isPalindrome("nitin")
assert isPalindrome("otto")
assert isPalindrome("madam")
assert isPalindrome("racecar")
assert isPalindrome("xerox")==False
